### PR TITLE
Added TravisCI Build + Badge

### PR DESCRIPTION
**Pull request by mchiodo**
We can still use Jenkins, but we can add this now, it already works.

### CODE REVIEW

**Comment by mchiodo** [comment]
You'll have to modify this to point to the illWill2Survive repo.  Right now it points to my fork

**Comment by dcartertwo** [comment]
merged.

**Comment by JarenGlover** [comment]
test - does this response come to your email?

On Sat, Jan 11, 2014 at 8:44 PM, Dan Carter notifications@github.comwrote:

> merged.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/illWill2Survive/Fuel-OD/pull/2#issuecomment-32112860
> .

## 

Jaren Glover
www.jarenglover.com http://jarenglover.com

**Comment by mchiodo** [comment]
ya

On Sun, Jan 12, 2014 at 9:29 PM, Jaren Glover notifications@github.comwrote:

> test - does this response come to your email?
> 
> On Sat, Jan 11, 2014 at 8:44 PM, Dan Carter notifications@github.comwrote:
> 
> > merged.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/illWill2Survive/Fuel-OD/pull/2#issuecomment-32112860>
> > .
> 
> ## 
> 
> Jaren Glover
> www.jarenglover.com http://jarenglover.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/illWill2Survive/Fuel-OD/pull/2#issuecomment-32142078
> .

## 

_Michael A Chiodo_mac5382@gmail.com
412-759-7467

**Pull request merged**
